make BaseHapiFhirDao.getDao() synchronized
avoid:
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 Bad Request: Unable to process request, this server does not know how to handle resources of type Organization